---
- name: Ensure pmm-agent is running
  ansible.builtin.service:
    enabled: true
    name: pmm-agent
    state: started

- name: Check if client is already connected to a PMM server
  ansible.builtin.command: pmm-admin status --json
  changed_when: false
  failed_when: false
  no_log: true
  register: _pmm_status

- name: Load PMM status into an Ansible variable
  ansible.builtin.set_fact:
    _pmm_status: "{{ (_pmm_status.stdout | from_json) }}"

- name: Connect PMM client to PMM server
  ansible.builtin.command: >
    pmm-admin config
      --server-url {{ pmm_client_server_url }}
      {{ "--server-insecure-tls" if pmm_client_server_insecure_tls else "" }}
  changed_when: false
  no_log: true
  when:
    - _pmm_status.pmm_agent_status.connected is not defined or not _pmm_status.pmm_agent_status.connected

- name: Check if a service is already configured
  ansible.builtin.shell: pmm-admin list --json 2>&1
  changed_when: false
  ignore_errors: true
  register: _pmm_list

- name: Load PMM list into an Ansible variable
  ansible.builtin.set_fact:
    _pmm_list: "{{ (_pmm_list.stdout | from_json) }}"

- name: Configure PMM services
  ansible.builtin.command: >
    pmm-admin add {{ item.type }}
      {{ item.flags | d(omit) }}
      {{ item.name }}
  loop: "{{ pmm_client_services }}"
  changed_when: false
  when: _pmm_list.service is not defined or (item.name not in _pmm_list.service | map(attribute="service_name") | list)
